"""regenerate-shim CLI (spec 023 FR-014)."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

from .. import __version__ as FRAMEWORK_VERSION
from ..generator.scaffold import render_vault_shim
from ..pipeline.atomic_write import write_json, write_text
from ..spec.schema import SpecConfig
from ..spec.simple import load as load_spec

SHIM_SENTINEL = "Generated by research-framework"
SHIM_REL = "vault"
FINGERPRINT_REL = "_pipeline/shim-fingerprint.json"


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _classify(vault_dir: Path, shim_path: Path) -> str:
    if not shim_path.is_file():
        return "stock"
    text = shim_path.read_text(encoding="utf-8", errors="replace")
    if SHIM_SENTINEL not in text:
        return "customized"
    fp = vault_dir / FINGERPRINT_REL
    if not fp.is_file():
        return "unverified"
    try:
        recorded = json.loads(fp.read_text(encoding="utf-8")).get("sha256", "")
    except (OSError, json.JSONDecodeError):
        return "unverified"
    if recorded != _sha256_bytes(shim_path.read_bytes()):
        return "customized"
    return "stock"


def cmd_regenerate_shim(args: argparse.Namespace) -> int:
    vault_dir = Path(args.vault).resolve()
    spec_path = vault_dir / "research.spec.md"
    if not spec_path.is_file():
        print(f"ERROR: missing {spec_path}", file=sys.stderr)
        return 2
    try:
        parse_path = vault_dir / "_pipeline/spec-parse.json"
        if parse_path.is_file():
            spec = SpecConfig.from_dict(
                json.loads(parse_path.read_text(encoding="utf-8"))
            )
        else:
            spec = load_spec(spec_path, location=vault_dir)
    except Exception as exc:
        print(f"ERROR: cannot load spec: {exc}", file=sys.stderr)
        return 2
    shim_path = vault_dir / SHIM_REL
    classification = _classify(vault_dir, shim_path)
    if args.dry_run:
        print(f"[regenerate-shim] vault={vault_dir}", file=sys.stderr)
        print(f"[regenerate-shim] classification={classification}", file=sys.stderr)
        if args.json:
            print(
                json.dumps(
                    {
                        "vault": str(vault_dir),
                        "classification": classification,
                        "overwritten": False,
                        "dry_run": True,
                    },
                    indent=2,
                )
            )
        return 0
    if classification in {"customized", "unverified"} and not args.force:
        print(
            f"[regenerate-shim] shim is {classification}; re-run with --force",
            file=sys.stderr,
        )
        if args.json:
            print(
                json.dumps(
                    {
                        "vault": str(vault_dir),
                        "classification": classification,
                        "overwritten": False,
                    },
                    indent=2,
                )
            )
        return 2
    from ..generator.scaffold import should_preserve_user_owned_file

    if should_preserve_user_owned_file(vault_dir, SHIM_REL):
        print(
            f"[regenerate-shim] preserving user-owned {SHIM_REL}",
            file=sys.stderr,
        )
        if args.json:
            print(
                json.dumps(
                    {
                        "vault": str(vault_dir),
                        "classification": classification,
                        "overwritten": False,
                    },
                    indent=2,
                )
            )
        return 0
    body = render_vault_shim(vault_dir, spec)
    write_text(shim_path, body, mode=0o755)
    digest = _sha256_bytes(body.encode("utf-8"))
    fp = {
        "path": SHIM_REL,
        "sha256": digest,
        "framework_version": str(FRAMEWORK_VERSION),
        "rendered_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }
    write_json(vault_dir / FINGERPRINT_REL, fp)
    if args.json:
        print(
            json.dumps(
                {
                    "vault": str(vault_dir),
                    "path": SHIM_REL,
                    "sha256": digest,
                    "classification": classification,
                    "overwritten": True,
                    "framework_version": str(FRAMEWORK_VERSION),
                },
                indent=2,
            )
        )
    else:
        print(f"[regenerate-shim] vault={vault_dir}", file=sys.stderr)
        print(
            f"[regenerate-shim] wrote {SHIM_REL} (755), sha256={digest[:12]}...",
            file=sys.stderr,
        )
    return 0
