#!/usr/bin/env python3
"""Render the prompt corpus into ``docs/prompts/`` (issue #280).

Not one of the framework's live prompts was reproduced outside the code that
builds it. A clean-room reimplementer inherited the orchestration graph and
the JSON Schemas the outputs must satisfy, but not one line of the text that
makes a model produce conforming output — 2,374 lines of Jinja, five agent
definitions and 26 skill files, all of them reachable only by knowing where
to look.

This script is the fix, and the rule it enforces is: **never hand-copy a
prompt.** Every artifact below is either rendered here from its source or
recorded here by path and content hash. Editing a rendered copy is pointless
— the guard re-derives it from the source and fails.

Two treatments, and the split is deliberate:

* **Rendered verbatim** (``docs/prompts/<slug>.md``) — the Jinja templates.
  Their text does not otherwise exist in the repo in the form a model sees:
  they are rendered into a generated vault at scaffold time, so reading the
  repo tells you the template, not the prompt. Reproducing them verbatim is
  the only way the corpus carries them.

* **Recorded, not copied** — the 26 ``.agents/skills/*/SKILL.md`` files.
  These are already standalone, verbatim, tracked files. Copying them into
  ``docs/prompts/`` would create a second source for the same bytes, which
  is the exact duplication issue #281 was filed about. The manifest names
  each one, the stage that dispatches it, and its hash — so drift is still
  caught, without a second copy to drift *from*.

Every prompt-shaped file in the tree must be classified as one of the two,
or listed in ``NOT_A_PROMPT`` with a reason. A guard that had to be told
about each new prompt would fail open the first time someone forgot; this
one fails closed on anything it has not been told about.

Usage::

    python scripts/render_prompt_corpus.py            # write
    python scripts/render_prompt_corpus.py --check    # verify, write nothing

Exit codes: 0 clean, 1 drifted (``--check``), 2 an unclassified prompt file.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "docs" / "prompts"
MANIFEST = OUTPUT_DIR / "README.md"

_GENERATED_BANNER = (
    "<!-- GENERATED by scripts/render_prompt_corpus.py — DO NOT EDIT. "
    "Edit the source named below, then re-run the script. -->"
)


@dataclass(frozen=True)
class Prompt:
    """One prompt artifact.

    ``source`` is repo-relative. ``slug`` is the output basename for a
    rendered artifact, or ``None`` for one that is recorded only.
    """

    source: str
    role: str
    dispatched_by: str
    slug: str | None = None

    @property
    def is_rendered(self) -> bool:
        return self.slug is not None


# --- Rendered verbatim: the templates a vault is built from ---------------

_TEMPLATES: tuple[Prompt, ...] = (
    Prompt(
        source="templates/prompts/scout-prompt.md.j2",
        role="Topic discovery — produces `_pipeline/scout-report.json`.",
        dispatched_by="`pipeline scout` / the cycle runner's scout step",
        slug="scout-prompt",
    ),
    Prompt(
        source="templates/prompts/dfs-prompt.md.j2",
        role="Depth-first research — writes notes, produces "
        "`_pipeline/research-report.json`.",
        dispatched_by="`pipeline resume` / the cycle runner's research step",
        slug="dfs-prompt",
    ),
    Prompt(
        source="templates/commands/ask.md.j2",
        role="Vault-grounded answering, with the Principle IX two-tier citation block.",
        dispatched_by="`./vault ask` (interactive)",
        slug="command-ask",
    ),
    Prompt(
        source="templates/commands/research.md.j2",
        role="Operator-facing research entry point.",
        dispatched_by="`/research` inside a vault",
        slug="command-research",
    ),
    Prompt(
        source="templates/commands/write.md.j2",
        role="Document generation, with the Principle IX two-tier citation "
        "requirement.",
        dispatched_by="`./vault write` (see spec 077 § D2 — not currently runnable)",
        slug="command-write",
    ),
    Prompt(
        source="src/research_framework/agents/scout.md.j2",
        role="Scout agent definition.",
        dispatched_by="rendered to `.claude/commands/scout.md`",
        slug="agent-scout",
    ),
    Prompt(
        source="src/research_framework/agents/extract.md.j2",
        role="Extraction agent definition.",
        dispatched_by="rendered to `.claude/commands/extract.md`",
        slug="agent-extract",
    ),
    Prompt(
        source="src/research_framework/agents/verify.md.j2",
        role="Verification agent definition.",
        dispatched_by="rendered to `.claude/commands/verify.md`",
        slug="agent-verify",
    ),
    Prompt(
        source="src/research_framework/agents/report.md.j2",
        role="Weekly report agent definition — the `report` phase's prompt "
        "source (spec 075).",
        dispatched_by="rendered to `.claude/commands/report.md`",
        slug="agent-report",
    ),
    Prompt(
        source="src/research_framework/agents/pipeline.md.j2",
        role="Pipeline shim agent definition — shells out and shows the "
        "output verbatim.",
        dispatched_by="rendered to `.claude/commands/pipeline.md`",
        slug="agent-pipeline",
    ),
    Prompt(
        source="templates/note-type.md.j2",
        role="The note scaffold every generated note starts from (spec 079).",
        dispatched_by="note rendering at scaffold time",
        slug="note-type",
    ),
)


# --- Recorded, not copied: already-verbatim standalone files --------------
#
# `dispatched_by` names the settings.yaml stage whose `skill:` selects it,
# or "not dispatched by a stage" for the ones the pipeline never selects.

_SKILL_STAGES: dict[str, str] = {
    "ask-answer": "`stages.ask_answer`",
    "cycle-report": "`stages.cycle_report`",
    "default-update-spec": "`stages.default_update_spec`",
    "dfs-prompt-gen": "`stages.dfs_prompt_gen`",
    "doc-planner": "`stages.doc_planner`",
    "doc-writer": "`stages.doc_writer`",
    "final-report": "`stages.final_report`",
    "install-wizard": "`stages.install_wizard`",
    "model-router": "`stages.model_router`",
    "note-tagger": "`stages.note_tagger`",
    "note-writer": "`stages.note_writer`",
    "scout": "`stages.scout`",
    "source-relevance": "`stages.source_relevance`",
    "topic-classifier": "`stages.topic_classifier`",
    "topic-propose": "`stages.topic_propose`",
    "vault-spec": "`stages.vault_spec`",
    "verifier": "`stages.verifier`",
}

_SKILL_ROOT = ".agents/skills"


# --- Classified as not a prompt ------------------------------------------

NOT_A_PROMPT: dict[str, str] = {
    "templates/CLAUDE.md.j2": "agent *context*, not a dispatched prompt",
    "templates/AGENTS.md.j2": "agent *context*, not a dispatched prompt",
    "templates/README.md.j2": "vault documentation",
    "templates/vault-script.sh.j2": "the `./vault` shim (spec 077)",
    "templates/update_vault.py.j2": "a script",
    "templates/vault-config.yaml.j2": "configuration",
    "templates/claude-settings.json.j2": "configuration",
    "templates/vault-research.service.j2": "a systemd unit",
    "templates/index-files/_index.md.j2": "an index file, not a prompt",
    "templates/index-files/_graph.md.j2": "an index file, not a prompt",
    "templates/index-files/_concepts.md.j2": "an index file, not a prompt",
}

# Everything under these roots must be classified. `.claude/skills/` is
# excluded on purpose: those are spec-kit authoring skills for contributors
# to THIS repo, not prompts the framework dispatches at a vault.
_DISCOVERY_GLOBS: tuple[str, ...] = (
    "templates/**/*.j2",
    "src/research_framework/agents/*.md.j2",
    f"{_SKILL_ROOT}/*/SKILL.md",
)


def skill_prompts() -> list[Prompt]:
    """Every tracked skill file, in path order."""
    root = REPO_ROOT / _SKILL_ROOT
    if not root.is_dir():
        return []
    found = []
    for skill_md in sorted(root.glob("*/SKILL.md")):
        name = skill_md.parent.name
        found.append(
            Prompt(
                source=str(skill_md.relative_to(REPO_ROOT)),
                role=f"`{name}` skill.",
                dispatched_by=_SKILL_STAGES.get(
                    name, "not selected by any settings.yaml stage"
                ),
            )
        )
    return found


def all_prompts() -> list[Prompt]:
    return list(_TEMPLATES) + skill_prompts()


def discovered_sources() -> list[str]:
    found: set[str] = set()
    for pattern in _DISCOVERY_GLOBS:
        for path in REPO_ROOT.glob(pattern):
            if path.is_file():
                found.add(str(path.relative_to(REPO_ROOT)))
    return sorted(found)


def unclassified_sources() -> list[str]:
    """Prompt-shaped files that are neither rendered, recorded nor excused."""
    known = {p.source for p in all_prompts()} | set(NOT_A_PROMPT)
    return [src for src in discovered_sources() if src not in known]


def source_digest(prompt: Prompt) -> str:
    data = (REPO_ROOT / prompt.source).read_bytes()
    return hashlib.sha256(data).hexdigest()[:16]


def _fence_for(text: str) -> str:
    """A fence long enough to survive a body that contains backtick fences."""
    longest = 0
    run = 0
    for char in text:
        run = run + 1 if char == "`" else 0
        longest = max(longest, run)
    return "`" * max(3, longest + 1)


def render_one(prompt: Prompt) -> str:
    source_text = (REPO_ROOT / prompt.source).read_text(encoding="utf-8")
    fence = _fence_for(source_text)
    title = prompt.slug.replace("-", " ") if prompt.slug else prompt.source
    body = source_text if source_text.endswith("\n") else source_text + "\n"
    return (
        f"# Prompt: {title}\n\n"
        f"{_GENERATED_BANNER}\n\n"
        f"| | |\n| --- | --- |\n"
        f"| **Source** | `{prompt.source}` |\n"
        f"| **Role** | {prompt.role} |\n"
        f"| **Dispatched by** | {prompt.dispatched_by} |\n"
        f"| **Source sha256** | `{source_digest(prompt)}` |\n\n"
        f"Reproduced verbatim, including its placeholders. A vault gets this "
        f"text with the placeholders filled at scaffold or dispatch time.\n\n"
        f"{fence}\n{body}{fence}\n"
    )


def render_manifest() -> str:
    rendered = [p for p in all_prompts() if p.is_rendered]
    recorded = [p for p in all_prompts() if not p.is_rendered]
    lines = [
        "# The prompt corpus",
        "",
        _GENERATED_BANNER,
        "",
        "Every prompt this framework puts in front of a model, in one place "
        "(issue #280). A clean-room reimplementer needs the text, not a "
        "paraphrase of it: the orchestration graph and the JSON Schemas say "
        "what the output must look like, and only the prompt says how to get "
        "a model to produce it.",
        "",
        "`scripts/render_prompt_corpus.py` writes this directory from the "
        "sources below and `--check` fails when any of them has moved on. "
        "Nothing here is hand-written, and editing a generated file changes "
        "nothing — re-run the script instead.",
        "",
        "## Rendered verbatim",
        "",
        "These are Jinja templates. Their text is rendered into a generated "
        "vault, so reading this repo shows you the template and not the "
        "prompt — reproducing them here is the only way the corpus carries "
        "them.",
        "",
        "| Prompt | Source | Role | Dispatched by | sha256 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for prompt in rendered:
        lines.append(
            f"| [`{prompt.slug}`]({prompt.slug}.md) | `{prompt.source}` | "
            f"{prompt.role} | {prompt.dispatched_by} | "
            f"`{source_digest(prompt)}` |"
        )
    lines += [
        "",
        "## Recorded, not copied",
        "",
        "These are already standalone, verbatim, tracked files. Copying them "
        "here would make one fact true in two places, which is what issue "
        "#281 was filed about — so the corpus names them and hashes them "
        "instead. The hash is what makes this an index rather than a claim: "
        "the guard recomputes it, so a skill file cannot change without this "
        "table changing with it.",
        "",
        "| Skill | Source | Dispatched by | sha256 |",
        "| --- | --- | --- | --- |",
    ]
    for prompt in recorded:
        name = Path(prompt.source).parent.name
        rel = "../../" + prompt.source
        lines.append(
            f"| [`{name}`]({rel}) | `{prompt.source}` | "
            f"{prompt.dispatched_by} | `{source_digest(prompt)}` |"
        )
    lines += [
        "",
        "## Deliberately not in the corpus",
        "",
        "| File | Why |",
        "| --- | --- |",
    ]
    for source, reason in sorted(NOT_A_PROMPT.items()):
        lines.append(f"| `{source}` | {reason} |")
    lines += [
        "",
        "`.claude/skills/` is excluded as a whole: those are spec-kit "
        "authoring skills for contributors to this repo, not prompts the "
        "framework dispatches at a vault.",
        "",
        "## What reads this directory",
        "",
        "`tests/docs/test_prompt_corpus_is_current.py` runs the renderer in "
        "`--check` mode, so a prompt edited without re-running the script "
        "fails the guard battery; and it fails on any prompt-shaped file the "
        "renderer has not been told how to classify, so the corpus cannot "
        "quietly stop being complete.",
        "",
    ]
    return "\n".join(lines)


def expected_files() -> dict[Path, str]:
    files = {MANIFEST: render_manifest()}
    for prompt in all_prompts():
        if prompt.is_rendered:
            assert prompt.slug is not None
            files[OUTPUT_DIR / f"{prompt.slug}.md"] = render_one(prompt)
    return files


def drifted() -> list[str]:
    problems = []
    for path, content in expected_files().items():
        rel = path.relative_to(REPO_ROOT)
        if not path.is_file():
            problems.append(f"{rel}: missing")
        elif path.read_text(encoding="utf-8") != content:
            problems.append(f"{rel}: stale")
    known = {p.relative_to(REPO_ROOT) for p in expected_files()}
    if OUTPUT_DIR.is_dir():
        for path in sorted(OUTPUT_DIR.glob("*.md")):
            if path.relative_to(REPO_ROOT) not in known:
                problems.append(f"{path.relative_to(REPO_ROOT)}: orphaned")
    return problems


def write() -> list[str]:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for path, content in expected_files().items():
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            written.append(str(path.relative_to(REPO_ROOT)))
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the corpus is current; write nothing",
    )
    args = parser.parse_args(argv)

    unclassified = unclassified_sources()
    if unclassified:
        print(
            "ERROR: prompt-shaped file(s) the corpus does not classify. Add "
            "each to _TEMPLATES, to the skills root, or to NOT_A_PROMPT with "
            "a reason:",
            file=sys.stderr,
        )
        for source in unclassified:
            print(f"  {source}", file=sys.stderr)
        return 2

    if args.check:
        problems = drifted()
        if problems:
            print("ERROR: docs/prompts/ is not current:", file=sys.stderr)
            for problem in problems:
                print(f"  {problem}", file=sys.stderr)
            print(
                "\nRun: python scripts/render_prompt_corpus.py",
                file=sys.stderr,
            )
            return 1
        print("docs/prompts/ is current.")
        return 0

    written = write()
    if written:
        for path in written:
            print(f"wrote {path}")
    else:
        print("docs/prompts/ already current; nothing written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
